export { MockService } from './src/main/ets/Service/MockService'

export { CourseDetailModel,
  CourseBookingInfo,
  CoachCourseInfo,
  CardInfo,
  UserCard,
  BookingRecordInfo,
  BookingInfo,
  BookState,
  OrderInfo,
  Account,
  OrderState,
  OrderType,
  SportTypeEnum,
  SportType,
  TeachType,
  ConsumeType } from './src/main/ets/model/MockModel'

export { DateUtil } from './src/main/ets/Service/DateUtil'
